[package]
name = "uefi_std"
version = "0.1.0"
edition = "2018"

[dependencies]
uefi = { git = "https://gitlab.redox-os.org/redox-os/uefi.git" }
uefi_alloc = { git = "https://gitlab.redox-os.org/redox-os/uefi_alloc.git" }
